In [1]:
import numpy as np

In [3]:
arr1 = np.arange(10)

In [4]:
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
arr1.mean()

4.5

In [8]:
arr1.sum()

45

In [9]:
arr1.max()

9

In [10]:
arr1.min()

0

In [12]:
np.median(arr1)

4.5

In [17]:
arr1.std()

2.8722813232690143

In [19]:
arr1.var()

8.25

In [20]:
np.sqrt(8.25)

2.8722813232690143

In [26]:
np.corrcoef(arr1)

1.0

In [27]:
arr2 = arr1+arr1

In [32]:
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr2 = arr2.reshape(2,5)

In [34]:
arr2.max()

18

In [35]:
arr2.min()

0

In [36]:
arr2.sum()

90

In [46]:
arr2.std(), arr1.std()

(5.744562646538029, 2.8722813232690143)

In [49]:
5.744562646538029 / 2.8722813232690143

2.0

In [45]:
arr2.var(), arr1.var()

(33.0, 8.25)

In [48]:
33.0 / 8.25

4.0

In [44]:
np.median(arr2), np.median(arr1)

(9.0, 4.5)

In [50]:
9.0 / 4.5

2.0

In [6]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [7]:
np.logspace(10,30,15,base=2)

array([1.02400000e+03, 2.75640359e+03, 7.41968826e+03, 1.99723197e+04,
       5.37614979e+04, 1.44715221e+05, 3.89544487e+05, 1.04857600e+06,
       2.82255728e+06, 7.59776078e+06, 2.04516554e+07, 5.50517738e+07,
       1.48188386e+08, 3.98893555e+08, 1.07374182e+09])