In [1]:
import numpy as np

## numpy.linspace

In [2]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [3]:
1.-1.47368421,  1.94736842-2.42105263  # difference between values

(-0.47368421000000005, -0.47368421000000005)

In [4]:
1.-3.36842105, 1.47368421-3.84210526, 1.94736842-4.31578947, 2.42105263-4.78947368

(-2.36842105, -2.36842105, -2.3684210500000002, -2.3684210500000002)

## numpy.logspace

In [5]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [6]:
np.logspace(1,10,num=10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [7]:
np.logspace(1,10,num=10,base=3)

array([3.0000e+00, 9.0000e+00, 2.7000e+01, 8.1000e+01, 2.4300e+02,
       7.2900e+02, 2.1870e+03, 6.5610e+03, 1.9683e+04, 5.9049e+04])

## NumPy - Indexing & Slicing Technique

### Indexing Single Dimension

In [8]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
arr[8]

18

In [10]:
arr[5]

15

### Slicing Single Dimension

In [11]:
arr[3:7]

array([13, 14, 15, 16])

In [12]:
arr[2:7:2]

array([12, 14, 16])

### Indexing Multi Dimension

In [13]:
ndarr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

ndarr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
ndarr[1]

array([40, 50, 60])

In [15]:
ndarr[1][2]

60

### Slicing Multi Dimension

In [16]:
ndarr[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
ndarr[0:2,1]

array([20, 50])

In [18]:
ndarr[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [19]:
ndarr[0:2,0:3:2]

array([[10, 30],
       [40, 60]])

###  Only Columns

In [20]:
ndarr[0:3,1:2]

array([[20],
       [50],
       [80]])

## numpy.diag

In [21]:
arr1 = np.arange(100,190,10).reshape(3,3)
arr1

array([[100, 110, 120],
       [130, 140, 150],
       [160, 170, 180]])

In [22]:
np.diag(arr1)

array([100, 140, 180])

## To Check Condition For A Value In Array

In [23]:
arr1

array([[100, 110, 120],
       [130, 140, 150],
       [160, 170, 180]])

In [26]:
arr1 > 130

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [27]:
arr1[arr1 > 130]

array([140, 150, 160, 170, 180])

## Broadcasting

### Single Dimensional Arrays

In [28]:
a1 = np.array([1, 2, 3, 4])
b1 = np.array([10, 20, 30, 40])

a1, b1

(array([1, 2, 3, 4]), array([10, 20, 30, 40]))

In [29]:
a1 + b1

array([11, 22, 33, 44])

In [30]:
a1 - b1

array([ -9, -18, -27, -36])

In [33]:
a1 * b1

array([ 10,  40,  90, 160])

In [35]:
a1 / b1

array([0.1, 0.1, 0.1, 0.1])

### Multi Dimensional Arrrays

In [36]:
m1 = np.array([
    [0.0, 0.0, 0.0],
    [10.0, 10.0, 10.0],
    [20.0, 20.0, 20.0],
    [30.0, 30.0, 30.0]
])

m1

array([[ 0.,  0.,  0.],
       [10., 10., 10.],
       [20., 20., 20.],
       [30., 30., 30.]])

In [37]:
m2 = np.array([1.0, 2.0, 3.0])

m2

array([1., 2., 3.])

In [38]:
m1 + m2

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [39]:
m1 - m2

array([[-1., -2., -3.],
       [ 9.,  8.,  7.],
       [19., 18., 17.],
       [29., 28., 27.]])

In [40]:
m1 * m2

array([[ 0.,  0.,  0.],
       [10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [41]:
m1  / m2

array([[ 0.        ,  0.        ,  0.        ],
       [10.        ,  5.        ,  3.33333333],
       [20.        , 10.        ,  6.66666667],
       [30.        , 15.        , 10.        ]])

In [42]:
m1 + m1

array([[ 0.,  0.,  0.],
       [20., 20., 20.],
       [40., 40., 40.],
       [60., 60., 60.]])

In [43]:
m1 - m1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
m1 * m1

array([[  0.,   0.,   0.],
       [100., 100., 100.],
       [400., 400., 400.],
       [900., 900., 900.]])

In [45]:
m1 / m1

<ipython-input-45-b8e16df1d8ef>:1: RuntimeWarning: invalid value encountered in true_divide
  m1 / m1


array([[nan, nan, nan],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## Iterating Into An Array

In [46]:
arr = np.arange(0,60,5).reshape(3,4)
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

### numpy.nditer

In [47]:
for item in np.nditer(arr):
    print(item)

0
5
10
15
20
25
30
35
40
45
50
55


## NumPy Array Manipulation :

In [48]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

#### ndarray.reshape

In [49]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [50]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

#### ndarray.flat

In [51]:
arr = np.arange(10,18).reshape(4,2)

In [52]:
arr.flat[3]

13

#### ndarray.flatten

In [53]:
arr.flatten()

array([10, 11, 12, 13, 14, 15, 16, 17])

#### ndarray.ravel

In [54]:
arr = np.arange(10,18).reshape(4,2)

In [55]:
arr.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17])

### Transpose

In [56]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### numpy.transpose

In [57]:
np.transpose(arr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])