In [1]:
import numpy as np

## numpy.sort

In [2]:
arr = np.array([[3,4],[9,1]])
arr

array([[3, 4],
       [9, 1]])

In [3]:
np.sort(arr)

array([[3, 4],
       [1, 9]])

In [4]:
np.sort(arr, axis=0)  # sorting on the basis of columns

array([[3, 1],
       [9, 4]])

In [5]:
np.sort(arr, axis=1)  # sorting on the basis of rows

array([[3, 4],
       [1, 9]])

## numpy.argsort

In [6]:
x = np.array([3,1,2])
x

array([3, 1, 2])

In [7]:
y = np.argsort(x)
y

array([1, 2, 0], dtype=int64)

## numpy.lexsort

In [8]:
name = ('dharmesh','sarvesh','ramesh','suresh')
year = ('fy','sy','sy','fy')

In [9]:
res = np.lexsort((year, name))
res

array([0, 2, 1, 3], dtype=int64)

In [10]:
[name[i]+" "+year[i] for i in res]

['dharmesh fy', 'ramesh sy', 'sarvesh sy', 'suresh fy']

In [11]:
a1 = [1,5,1,4,3,4,4]
b1 = [9,4,0,4,0,2,1]

In [12]:
res = np.lexsort((b1,a1))
res

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [13]:
[(a1[i],b1[i]) for i in res]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

## numpy.where

In [14]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
y = np.where(x > 5)
y

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [16]:
x[y]

array([6, 7, 8])

## numpy.extract

In [17]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
condition = np.mod(x,2) == 0
condition

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [19]:
np.extract(condition, x)

array([0, 2, 4, 6, 8])