# Introduction To NumPy

### Operations using NumPy

### Installing NumPy Library

In [1]:
!pip install numpy --quiet

### Importing NumPy Library

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

## NumPy - ndarray Object

### How To Declare NumPy Array

In [6]:
my_arr1 = np.array([1, 2, 3, 4, 5])  # single dimension array

In [7]:
print(my_arr1)

[1 2 3 4 5]


In [8]:
type(my_arr1)

numpy.ndarray

In [9]:
my_arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # multi dimensional array

In [10]:
print(my_arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
arr_c = np.array([1, 2, 3, 4], dtype=complex)  # complex datatype

In [12]:
print(arr_c)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


### NumPy Data Types

## NumPy - Array Attributes

### ndarray.shape :

In [13]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

In [14]:
print(arr)

[[10 20 30]
 [40 50 60]]


In [15]:
arr.shape

(2, 3)

In [16]:
# resizing the array

arr.shape = (3,2)

In [17]:
arr

array([[10, 20],
       [30, 40],
       [50, 60]])

In [18]:
arr.shape

(3, 2)

### ndarray.ndim :

In [19]:
arr.ndim

2

### ndarray.itemsize

In [20]:
arr.itemsize

4

In [53]:
num = np.array([1,2,3,4,5],dtype=np.float32)
num1 = np.array([1,2,3,4,5],dtype=np.int64)

In [54]:
num.itemsize

4

In [55]:
num1.itemsize

8

### ndarray.reshape

In [21]:
arr = arr.reshape(2,3)

In [22]:
print(arr)

[[10 20 30]
 [40 50 60]]


In [23]:
arr.shape

(2, 3)

## numpy.arange

In [25]:
num = np.arange(30)

In [26]:
print(num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [27]:
num.ndim

1

In [28]:
num.shape

(30,)

In [29]:
num = num.reshape(5,6)

In [30]:
print(num)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [31]:
num.shape

(5, 6)

In [32]:
num.ndim

2

In [42]:
num1 = np.arange(24)

In [43]:
print(num1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [44]:
num1 = num1.reshape(2,4,3)

In [45]:
print(num1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [46]:
num1.ndim

3

In [47]:
num1.shape

(2, 4, 3)

## numpy.empty

In [66]:
x = np.empty([3,2], dtype=int)

In [71]:
print(x)

[[     120 26218842]
 [       0        0]
 [  131074      115]]


In [72]:
x.shape

(3, 2)

## numpy.zeros

In [73]:
zero_arr = np.zeros([3,2],dtype=int)

In [74]:
print(zero_arr)

[[0 0]
 [0 0]
 [0 0]]


## numpy.ones

In [75]:
ones = np.ones([3,3],dtype=np.int8)

In [76]:
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## numpy.arange

In [77]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [80]:
np.arange(10, 30, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])